### ISSUE TITLE
setwebpass

### ISSUE THREAD

**Issue by ADronov1** [ton-blockchain/mytonctrl#104]
MyTonInstaller> setwebpass
Set a new password for the web admin panel:
Repeat password:
Traceback (most recent call last):
  File "/usr/src/mtc-jsonrpc/mtc-jsonrpc.py", line 582, in <module>
    Init()
  File "/usr/src/mtc-jsonrpc/mtc-jsonrpc.py", line 547, in Init
    SetWebPassword()
  File "/usr/src/mtc-jsonrpc/mtc-jsonrpc.py", line 529, in SetWebPassword
    make_ssl_devcert(sslKeyPath, host=ip)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 528, in make_ssl_devcert
    cert, pkey = generate_adhoc_ssl_pair(cn=cn)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 469, in generate_adhoc_ssl_pair
    raise TypeError(
TypeError: Using ad-hoc certificates requires the cryptography library.

MyTonInstaller>

what's the error?

**Comment by pakkonen** [comment]
how did you solve this problem?
