### ISSUE TITLE
unable to install run full node because ifconfig.me blocks the ip finding request 

### ISSUE THREAD

**Issue by IRGC** [ton-blockchain/mytonctrl#118]
unable to install full node because ifconfig.me blocks the request that finds public ip of the server.
can we use different domain or some other way to find the ip?
also is there a way to manually specifying it?

```

Step, [02-03-2023 12:45]
[5/6] Downloading config files
--2023-03-02 07:14:09--  https://ton-blockchain.github.io/global.config.json
Resolving ton-blockchain.github.io (ton-blockchain.github.io)... 185.199.111.153, 185.199.110.153, 185.199.108.153, ...
Connecting to ton-blockchain.github.io (ton-blockchain.github.io)|185.199.111.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13807 (13K) [application/json]
Saving to: ‘global.config.json’

global.config.json                              100%[====================================================================================================>]  13.48K  --.-KB/s    in 0s

2023-03-02 07:14:09 (88.5 MB/s) - ‘global.config.json’ saved [13807/13807]

[6/6] TON software installation complete
[3/4] Launching the mytoninstaller.py
[debug]   02.03.2023, 07:14:09.342 (UTC)  <Logging>     Start WritingLogFile thread.
[debug]   02.03.2023, 07:14:09.342 (UTC)  <SelfTesting> Start SelfTesting thread.
[info]    02.03.2023, 07:14:09.342 (UTC)  <MainThread>  Start program '/usr/src/mytonctrl/mytoninstaller.py'
[debug]   02.03.2023, 07:14:09.342 (UTC)  <MainThread>  start FirstMytoncoreSettings fuction
[debug]   02.03.2023, 07:14:09.577 (UTC)  <MainThread>  Start/restart mytoncore service
[debug]   02.03.2023, 07:14:09.586 (UTC)  <MainThread>  start FirstNodeSettings fuction
[debug]   02.03.2023, 07:14:09.973 (UTC)  <MainThread>  Use addr:
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/</code> from this server.</h2>
<h2></h2>
</body></html>
:53004
[debug]   02.03.2023, 07:14:09.973 (UTC)  <MainThread>  First start validator - create config.json
[ 1][t 0][2023-03-02 07:14:09.980304401][validator-engine.cpp:3607]     failed to parse options: [Error : 0 : Failed to resolve host: Name or service not known]
[debug]   02.03.2023, 07:14:09.981 (UTC)  <MainThread>  Chown ton-work dir
[debug]   02.03.2023, 07:14:09.984 (UTC)  <MainThread>  Start/restart validator service
[debug]   02.03.2023, 07:14:09.990 (UTC)  <MainThread>  sleep 10 sec
[debug]   02.03.2023, 07:14:20.000 (UTC)  <MainThread>  start EnableValidatorConsole function
[debug]   02.03.2023, 07:14:20.017 (UTC)  <MainThread>  Start/restart validator service
[debug]   02.03.2023, 07:14:20.023 (UTC)  <MainThread>  sleep 10 sec
[debug]   02.03.2023, 07:14:30.175 (UTC)  <MainThread>  start CreateWallet function
[debug]   02.03.2023, 07:14:30.195 (UTC)  <MainThread>  start GetLocalWallet function
[debug]   02.03.2023, 07:14:30.195 (UTC)  <MainThread>  start GetWalletFromFile function
[debug]   02.03.2023, 07:14:30.195 (UTC)  <MainThread>  start GetConfig function (12)
[warning] 02.03.2023, 07:14:33.201 (UTC)  <MainThread>  GetValidatorStatus warning: Command '['/usr/bin/ton/validator-engine-console/validator-engine-console', '-k', '/var/ton-work/keys/client', '-p', '/var/ton-work/keys/server.pub', '-a', '127.0.0.1:63361', '-v', '0', '--cmd', 'getstats']' timed out after 3 seconds
[debug]   02.03.2023, 07:14:35.146 (UTC)  <MainThread>  start GetConfig function (15)
[debug]   02.03.2023, 07:14:37.614 (UTC)  <MainThread>  start WalletVersion2Wallet function
[debug]   02.03.2023, 07:14:37.615 (UTC)  <MainThread>  start CreateNewKey function
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytoncore.py", line 4434, in <module>
    Init()
  File "/usr/src/mytonctrl/mytoncore.py", line 3902, in Init
    Event(eventName)
  File "/usr/src/mytonctrl/mytoncore.py", line 3921, in Event
    EnableVcEvent()
  File "/usr/src/mytonctrl/mytoncore.py", line 3935, in EnableVcEvent
    adnlAddr = ton.CreateNewKey()
  File "/usr/src/mytonctrl/mytoncore.py", line 1232, in CreateNewKey
    result = self.validatorConsole.Run("newkey")
  File "/usr/src/mytonctrl/mytoncore.py", line 66, in Run
    process = subprocess.run(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout)

Step, [02-03-2023 12:45]

  File "/usr/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1982, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.9/subprocess.py", line 1178, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['/usr/bin/ton/validator-engine-console/validator-engine-console', '-k', '/var/ton-work/keys/client', '-p', '/var/ton-work/keys/server.pub', '-a', '127.0.0.1:63361', '-v', '0', '--cmd', 'newkey']' timed out after 3 seconds
[debug]   02.03.2023, 07:14:40.651 (UTC)  <MainThread>  Start/restart mytoncore service
[debug]   02.03.2023, 07:14:40.664 (UTC)  <MainThread>  start EnableLiteServer function
[debug]   02.03.2023, 07:14:40.664 (UTC)  <MainThread>  generate liteserver key
[debug]   02.03.2023, 07:14:40.670 (UTC)  <MainThread>  move key
[debug]   02.03.2023, 07:14:40.673 (UTC)  <MainThread>  chown 1
[debug]   02.03.2023, 07:14:40.675 (UTC)  <MainThread>  chown 2
[debug]   02.03.2023, 07:14:40.677 (UTC)  <MainThread>  read vconfig
[debug]   02.03.2023, 07:14:40.677 (UTC)  <MainThread>  prepare vconfig
[debug]   02.03.2023, 07:14:40.677 (UTC)  <MainThread>  write vconfig
[debug]   02.03.2023, 07:14:40.677 (UTC)  <MainThread>  Start/restart validator service
[debug]   02.03.2023, 07:14:40.683 (UTC)  <MainThread>  sleep 10 sec
[debug]   02.03.2023, 07:14:50.693 (UTC)  <MainThread>  read mconfig
[debug]   02.03.2023, 07:14:50.694 (UTC)  <MainThread>  edit mytoncore config file
[debug]   02.03.2023, 07:14:50.694 (UTC)  <MainThread>  write mconfig
[debug]   02.03.2023, 07:14:50.694 (UTC)  <MainThread>  Start/restart mytoncore service
[debug]   02.03.2023, 07:14:50.709 (UTC)  <MainThread>  Backup validator config file 'config.json' to 'config.json.backup'
[debug]   02.03.2023, 07:14:50.711 (UTC)  <MainThread>  Backup mytoncore config file 'mytoncore.db' to 'mytoncore.db.backup'
[debug]   02.03.2023, 07:14:50.713 (UTC)  <MainThread>  start CreateSymlinks fuction
[4/4] Mytonctrl installation completed
```

**Comment by IRGC** [comment]
it looks like something wrong with accept header.
```
root@ton3:~# curl 'https://ifconfig.me' -H 'user-agent: python-requests/2.25.1' -H 'Connection: keep-alive' -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*'

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/</code> from this server.</h2>
<h2></h2>
</body></html>


root@ton3:~# curl 'https://ifconfig.me' -H 'user-agent: python-requests/2.25.1' -H 'Connection: keep-alive' -H 'Accept-Encoding: gzip, deflate'
123.123.123.123root@ton3:~#
```

**Comment by IRGC** [comment]
seems like the error is randomly thrown regardless of headers.

**Comment by yungwine** [comment]
fixed in d3362019
