### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' in clcf

### ISSUE THREAD

**Issue by UranusLin** [ton-blockchain/mytonctrl#121]
I run 
```
sudo bash install.sh -m lite -c https://ton.org/testnet-global.config.json
```
and 
```
MyTonCtrl> set sendTelemetry false
MyTonCtrl> installer
MyTonInstaller> clcf
```
but show 
```
[warning] 08.03.2023, 06:42:22.557 (UTC)  <MainThread>  GetValidatorStatus warning: ValidatorConsole error: Validator console is not settings
[debug]   08.03.2023, 06:42:26.597 (UTC)  <Logging>     Start WritingLogFile thread.
[debug]   08.03.2023, 06:42:26.597 (UTC)  <SelfTesting> Start SelfTesting thread.
[info]    08.03.2023, 06:42:26.597 (UTC)  <MainThread>  Start program '/usr/src/mytonctrl/mytoninstaller.py'
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytoninstaller.py", line 1049, in <module>
    General()
  File "/usr/src/mytonctrl/mytoninstaller.py", line 216, in General
    Event(name)
  File "/usr/src/mytonctrl/mytoninstaller.py", line 204, in Event
    CreateLocalConfig(initBlock)
  File "/usr/src/mytonctrl/mytoninstaller.py", line 152, in CreateLocalConfig
    liteServerConfig = GetLiteServerConfig()
  File "/usr/src/mytonctrl/mytoninstaller.py", line 127, in GetLiteServerConfig
    result["port"] = liteServer.get("port")
AttributeError: 'NoneType' object has no attribute 'get'
```

can anyone help me to solve this problem? thanks

**Comment by igroman787** [comment]
To use your local lightserver you need to install in full mode:
`sudo bash install.sh -m full -c https://ton.org/testnet-global.config.json`
