### ISSUE TITLE
The config file is broken

### ISSUE THREAD

**Issue by Parmanand0712** [ton-blockchain/mytonctrl#145]
Hi Team

after executing mytonctrl on commad prompt then below errors are coming - 

[warning] 28.10.2023, 13:14:51.942 (UTC)  <MainThread>  The config file is broken
local.db: {'config': {'logLevel': 'info', 'isLimitLogFile': True, 'isDeleteOldLogFile': False, 'isIgnorLogWarning': False, 'isStartOnlyOneProcess': True, 'memoryUsinglimit': 50, 'isLocaldbSaving': False, 'isWritingLogFile': True}}
[debug]   28.10.2023, 13:14:51.944 (UTC)  <MainThread>  Thread self_test started
[debug]   28.10.2023, 13:14:51.944 (UTC)  <MainThread>  Thread write_log started
[info]    28.10.2023, 13:14:51.944 (UTC)  <MainThread>  Start program /usr/src/mytonctrl/mytonctrl.py
Welcome to the console. Enter 'help' to display the help menu.
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytonctrl.py", line 1216, in <module>
    console.Run()
  File "/usr/src/mytonctrl/mypyconsole/mypyconsole.py", line 97, in Run
    self.startFunction()
  File "/usr/src/mytonctrl/mytonctrl.py", line 106, in PreUp
    check_vport()
  File "/usr/src/mytonctrl/mytonctrl.py", line 122, in check_vport
    vconfig = ton.GetValidatorConfig()
  File "/usr/src/mytonctrl/mytoncore.py", line 1929, in GetValidatorConfig
    result = self.validatorConsole.Run("getconfig")
  File "/usr/src/mytonctrl/mytoncore.py", line 66, in Run
    raise Exception("ValidatorConsole error: Validator console is not settings")
Exception: ValidatorConsole error: Validator console is not settings

how to solve it??

**Comment by XOP-EHOTOB** [comment]
+

**Comment by XOP-EHOTOB** [comment]
There is a solution?

> Hi Team
> 
> after executing mytonctrl on commad prompt then below errors are coming -
> 
> [warning] 28.10.2023, 13:14:51.942 (UTC) The config file is broken local.db: {'config': {'logLevel': 'info', 'isLimitLogFile': True, 'isDeleteOldLogFile': False, 'isIgnorLogWarning': False, 'isStartOnlyOneProcess': True, 'memoryUsinglimit': 50, 'isLocaldbSaving': False, 'isWritingLogFile': True}} [debug] 28.10.2023, 13:14:51.944 (UTC) Thread self_test started [debug] 28.10.2023, 13:14:51.944 (UTC) Thread write_log started [info] 28.10.2023, 13:14:51.944 (UTC) Start program /usr/src/mytonctrl/mytonctrl.py Welcome to the console. Enter 'help' to display the help menu. Traceback (most recent call last): File "/usr/src/mytonctrl/mytonctrl.py", line 1216, in console.Run() File "/usr/src/mytonctrl/mypyconsole/mypyconsole.py", line 97, in Run self.startFunction() File "/usr/src/mytonctrl/mytonctrl.py", line 106, in PreUp check_vport() File "/usr/src/mytonctrl/mytonctrl.py", line 122, in check_vport vconfig = ton.GetValidatorConfig() File "/usr/src/mytonctrl/mytoncore.py", line 1929, in GetValidatorConfig result = self.validatorConsole.Run("getconfig") File "/usr/src/mytonctrl/mytoncore.py", line 66, in Run raise Exception("ValidatorConsole error: Validator console is not settings") Exception: ValidatorConsole error: Validator console is not settings
> 
> how to solve it??

There is a solution?

**Comment by AVert** [comment]
Same error

**Comment by Supanut1911** [comment]
me same error

**Comment by Enton-72** [comment]
For some reason you need to login as user that will be used for mytoncore and then execute "sudo bash install.sh -m full"
This fixed the mentioned issue in my case.

**Comment by igroman787** [comment]
This error can occur in two cases:
1. Installation was performed without node/validator setup `bash install.sh -m lite`
2. The installation was performed for another user

Solution for the first option:
Need to uninstall and install again in full mode `bash install.sh -m full`

Solution for the second option:
Find which user the installation was performed for `ls -lh /var/ton-work/keys/`
Run mytonctrl as the user for whom it was installed

If this does not help, please send the installation logs that are displayed in the console.

**Comment by udi256** [comment]
I'm facing the same error even though I installed and ran it as a user without root privileges but with sudo privileges, and I installed it in full mode. I'm attaching a link to the installation process logs.
https://drive.google.com/file/d/1P4BiNidVBCrYJXHY8glqW2oFleO-VeUA/view?usp=sharing

**Comment by ubique** [comment]
_scripts/install.sh_  relies on **logname** utility  to get the name of the unprivileged user. If the initial ssh login happens under root account and then substitution to the unprivileged account happens (e.g. **su - user**) **logname** returns "root" and this breaks the installation process if you run it as required - I guess that owner of some file objects mistakenly is changed to root and the unprivileged user doesn't have an access to those objects.
