### ISSUE TITLE
during in isntall mytonctrl error:

### ISSUE THREAD

**Issue by diwobk** [ton-blockchain/mytonctrl#147]
[debug]   07.11.2023, 01:42:32.401 (UTC)  <MainThread>  start EnableVcEvent function
[debug]   07.11.2023, 01:42:32.401 (UTC)  <MainThread>  start CreateWallet function
[warning] 07.11.2023, 01:42:32.401 (UTC)  <MainThread>  CreateWallet error: Wallet already exists: validator_wallet_001
[debug]   07.11.2023, 01:42:32.401 (UTC)  <MainThread>  start GetLocalWallet function
[debug]   07.11.2023, 01:42:32.401 (UTC)  <MainThread>  start GetWalletFromFile function
[debug]   07.11.2023, 01:42:32.401 (UTC)  <MainThread>  start GetConfig function (12)
[warning] 07.11.2023, 01:42:32.410 (UTC)  <MainThread>  GetValidatorStatus warning: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytoncore.py", line 4250, in <module>
    Init()
  File "/usr/src/mytonctrl/mytoncore.py", line 3712, in Init
    Event(eventName)
  File "/usr/src/mytonctrl/mytoncore.py", line 3732, in Event
    EnableVcEvent()
  File "/usr/src/mytonctrl/mytoncore.py", line 3742, in EnableVcEvent
    wallet = ton.CreateWallet("validator_wallet_001", -1)
  File "/usr/src/mytonctrl/mytoncore.py", line 1806, in CreateWallet
    wallet = self.GetLocalWallet(name, version)
  File "/usr/src/mytonctrl/mytoncore.py", line 675, in GetLocalWallet
    wallet = self.GetWalletFromFile(walletPath, version)
  File "/usr/src/mytonctrl/mytoncore.py", line 693, in GetWalletFromFile
    self.AddrFile2Object(wallet)
  File "/usr/src/mytonctrl/mytoncore.py", line 726, in AddrFile2Object
    object.addrB64 = self.AddrFull2AddrB64(object.addrFull)
  File "/usr/src/mytonctrl/mytoncore.py", line 3092, in AddrFull2AddrB64
    testnet = self.IsTestnet()
  File "/usr/src/mytonctrl/mytoncore.py", line 3662, in IsTestnet
    networkName = self.GetNetworkName()
  File "/usr/src/mytonctrl/mytoncore.py", line 3630, in GetNetworkName
    config12 = self.GetConfig(12)
  File "/usr/src/mytonctrl/mytoncore.py", line 1094, in GetConfig
    result = self.liteClient.Run(cmd)
  File "/usr/src/mytonctrl/mytoncore.py", line 44, in Run
    process = subprocess.run(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1154, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.10/subprocess.py", line 2022, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.10/subprocess.py", line 1198, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['/usr/bin/ton/lite-client/lite-client', '--global-config', '/usr/bin/ton/global.config.json', '--verbosity', '0', '--cmd', 'getconfig 12']' timed out after 3 seconds**

**Comment by tsivarev** [comment]
It looks like your local node is not working. I would advise looking at the node logs and looking for errors:
/var/ton-work/log.thread*

**Comment by igroman787** [comment]
This error was fixed in the `mytonctrl2` branch. Installation will no longer use public lite-servers:
https://github.com/ton-blockchain/mytonctrl/commit/ac72a30987dd9343aa77e796eb59ce3d73ba34a0

And soon `mytonctrl2` branch will be merge into the `master` branch
