### ISSUE TITLE
Exception: ValidatorConsole error: Validator console is not settings

### ISSUE THREAD

**Issue by jw-star** [ton-blockchain/mytonctrl#151]
Ubuntu 22.04 LTS

root

bash install.sh -m lite -d

```
root@vultr:~# mytonctrl
[debug]   11.12.2023, 13:19:07.709 (UTC)  <MainThread>  Thread self_test started
[debug]   11.12.2023, 13:19:07.710 (UTC)  <MainThread>  Thread write_log started
[info]    11.12.2023, 13:19:07.710 (UTC)  <MainThread>  Start program `/usr/src/mytonctrl/mytonctrl.py`
Welcome to the console. Enter 'help' to display the help menu.
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytonctrl.py", line 1216, in <module>
    console.Run()
  File "/usr/src/mytonctrl/mypyconsole/mypyconsole.py", line 97, in Run
    self.startFunction()
  File "/usr/src/mytonctrl/mytonctrl.py", line 106, in PreUp
    check_vport()
  File "/usr/src/mytonctrl/mytonctrl.py", line 122, in check_vport
    vconfig = ton.GetValidatorConfig()
  File "/usr/src/mytonctrl/mytoncore.py", line 1929, in GetValidatorConfig
    result = self.validatorConsole.Run("getconfig")
  File "/usr/src/mytonctrl/mytoncore.py", line 66, in Run
    raise Exception("ValidatorConsole error: Validator console is not settings")
Exception: ValidatorConsole error: Validator console is not settings

```

**Comment by UranusLin** [comment]
We have same issue after run update on mytonctrl
```
[4/4] Mytonctrl installation completed
root@ton01-stg:~# mytonctrl
[debug]   15.12.2023, 07:04:40.604 (UTC)  <MainThread>  Thread self_test started
[debug]   15.12.2023, 07:04:40.605 (UTC)  <MainThread>  Thread write_log started
[info]    15.12.2023, 07:04:40.605 (UTC)  <MainThread>  Start program `/usr/src/mytonctrl/mytonctrl.py`
Welcome to the console. Enter 'help' to display the help menu.
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytonctrl.py", line 1216, in <module>
    console.Run()
  File "/usr/src/mytonctrl/mypyconsole/mypyconsole.py", line 97, in Run
    self.startFunction()
  File "/usr/src/mytonctrl/mytonctrl.py", line 106, in PreUp
    check_vport()
  File "/usr/src/mytonctrl/mytonctrl.py", line 122, in check_vport
    vconfig = ton.GetValidatorConfig()
  File "/usr/src/mytonctrl/mytoncore.py", line 1929, in GetValidatorConfig
    result = self.validatorConsole.Run("getconfig")
  File "/usr/src/mytonctrl/mytoncore.py", line 66, in Run
    raise Exception("ValidatorConsole error: Validator console is not settings")
Exception: ValidatorConsole error: Validator console is not settings
```

**Comment by jw-star** [comment]
@UranusLin It seems that you must run a full node, but there is no such high configuration

**Comment by Suihuan** [comment]
same issue!

[4/4] Mytonctrl installation completed
root@ton01-stg:~# mytonctrl
[debug]   15.12.2023, 07:04:40.604 (UTC)  <MainThread>  Thread self_test started
[debug]   15.12.2023, 07:04:40.605 (UTC)  <MainThread>  Thread write_log started
[info]    15.12.2023, 07:04:40.605 (UTC)  <MainThread>  Start program `/usr/src/mytonctrl/mytonctrl.py`
Welcome to the console. Enter 'help' to display the help menu.
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytonctrl.py", line 1216, in <module>
    console.Run()
  File "/usr/src/mytonctrl/mypyconsole/mypyconsole.py", line 97, in Run
    self.startFunction()
  File "/usr/src/mytonctrl/mytonctrl.py", line 106, in PreUp
    check_vport()
  File "/usr/src/mytonctrl/mytonctrl.py", line 122, in check_vport
    vconfig = ton.GetValidatorConfig()
  File "/usr/src/mytonctrl/mytoncore.py", line 1929, in GetValidatorConfig
    result = self.validatorConsole.Run("getconfig")
  File "/usr/src/mytonctrl/mytoncore.py", line 66, in Run
    raise Exception("ValidatorConsole error: Validator console is not settings")
Exception: ValidatorConsole error: Validator console is not settings

**Comment by execc** [comment]
Same issue!

**Comment by tsivarev** [comment]
It was a typo in the documentation. Use 'bash install.sh -m **full** -d'

**Comment by jw-star** [comment]
@tsivarev I just need to install the lite node, the full node is too demanding on the device

**Comment by AbelGate** [comment]
same issue

```bash
sudo mytonctrl 
[warning] 18.12.2023, 13:17:53.162 (UTC)  <MainThread>  The config file is broken
local.db: {'config': {'logLevel': 'info', 'isLimitLogFile': True, 'isDeleteOldLogFile': False, 'isIgnorLogWarning': False, 'isStartOnlyOneProcess': True, 'memoryUsinglimit': 50, 'isLocaldbSaving': False, 'isWritingLogFile': True}}
[debug]   18.12.2023, 13:17:53.164 (UTC)  <MainThread>  Thread self_test started
[debug]   18.12.2023, 13:17:53.165 (UTC)  <MainThread>  Thread write_log started
[info]    18.12.2023, 13:17:53.165 (UTC)  <MainThread>  Start program `/usr/src/mytonctrl/mytonctrl.py`
Welcome to the console. Enter 'help' to display the help menu.
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytonctrl.py", line 1216, in <module>
    console.Run()
  File "/usr/src/mytonctrl/mypyconsole/mypyconsole.py", line 97, in Run
    self.startFunction()
  File "/usr/src/mytonctrl/mytonctrl.py", line 106, in PreUp
    check_vport()
  File "/usr/src/mytonctrl/mytonctrl.py", line 122, in check_vport
    vconfig = ton.GetValidatorConfig()
  File "/usr/src/mytonctrl/mytoncore.py", line 1929, in GetValidatorConfig
    result = self.validatorConsole.Run("getconfig")
  File "/usr/src/mytonctrl/mytoncore.py", line 66, in Run
    raise Exception("ValidatorConsole error: Validator console is not settings")
Exception: ValidatorConsole error: Validator console is not settings
```

**Comment by tsivarev** [comment]
Write me on Telegram: @tsivarev

**Comment by xyunsh** [comment]
Same

**Comment by mimikadze** [comment]
Got the same issue making prerequisites step like described on https://docs.ton.org/participate/run-nodes/full-node#step-by-step-instructions

```
Login to your server as a non-root user with sudo privileges.

If you don't have a non-root user, login as root and create it:

sudo adduser <username>

Add your user to the sudo group:
sudo usermod -aG sudo <username>

Switch to your non-root user:
su - <username>
```

It turns out that you should log on remote server as non-root user and then run install script. Don't escalate privileges like `su - ton`

**Comment by AlexSpain** [comment]
same issue
I log on remote server as non-root user and then run install script. Don't escalate privileges like su - ton

**Comment by recfrf44** [comment]
Ubuntu 18.04 LTS (Bionic Beaver) | OK - lie, not work
Ubuntu 20.04 LTS (Focal Fossa) | OK - work only _Ubuntu server_ iso, and only full install, lite not work
Ubuntu 22.04 LTS (Jammy Jellyfish) | OK - work only _Ubuntu server_ iso, and only full install, lite not work
The light version does not work in principle, in any case there will be an error "Validator console is not settings"

**Comment by bixia** [comment]
the issue still exists
```js
➜  download mytonctrl
[warning] 29.05.2024, 15:20:08.335 (UTC)  <MainThread>  The config file is broken
local.db: {'config': {'logLevel': 'info', 'isLimitLogFile': True, 'isDeleteOldLogFile': False, 'isIgnorLogWarning': False, 'isStartOnlyOneProcess': True, 'memoryUsinglimit': 50, 'isLocaldbSaving': False, 'isWritingLogFile': True}}
[debug]   29.05.2024, 15:20:08.335 (UTC)  <MainThread>  Thread self_test started
[debug]   29.05.2024, 15:20:08.335 (UTC)  <MainThread>  Thread write_log started
[info]    29.05.2024, 15:20:08.335 (UTC)  <MainThread>  Start program `/usr/src/mytonctrl/mytonctrl.py`
Welcome to the console. Enter 'help' to display the help menu.
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytonctrl.py", line 1228, in <module>
    console.Run()
  File "/usr/src/mytonctrl/mypyconsole/mypyconsole.py", line 97, in Run
    self.startFunction()
  File "/usr/src/mytonctrl/mytonctrl.py", line 114, in PreUp
    check_vport()
  File "/usr/src/mytonctrl/mytonctrl.py", line 130, in check_vport
    vconfig = ton.GetValidatorConfig()
  File "/usr/src/mytonctrl/mytoncore.py", line 1951, in GetValidatorConfig
    result = self.validatorConsole.Run("getconfig")
  File "/usr/src/mytonctrl/mytoncore.py", line 67, in Run
    raise Exception("ValidatorConsole error: Validator console is not settings")
Exception: ValidatorConsole error: Validator console is not settings
```

**Comment by tresting** [comment]
> the issue still exists

>     raise Exception("ValidatorConsole error: Validator console is not settings")
> Exception: ValidatorConsole error: Validator console is not settings
> ```

and will exist, the light version will not work, since the developers are stupid and don’t talk about it

**Comment by AbelGate** [comment]
> same issue
> 
> ```shell
> sudo mytonctrl 
> [warning] 18.12.2023, 13:17:53.162 (UTC)  <MainThread>  The config file is broken
> local.db: {'config': {'logLevel': 'info', 'isLimitLogFile': True, 'isDeleteOldLogFile': False, 'isIgnorLogWarning': False, 'isStartOnlyOneProcess': True, 'memoryUsinglimit': 50, 'isLocaldbSaving': False, 'isWritingLogFile': True}}
> [debug]   18.12.2023, 13:17:53.164 (UTC)  <MainThread>  Thread self_test started
> [debug]   18.12.2023, 13:17:53.165 (UTC)  <MainThread>  Thread write_log started
> [info]    18.12.2023, 13:17:53.165 (UTC)  <MainThread>  Start program `/usr/src/mytonctrl/mytonctrl.py`
> Welcome to the console. Enter 'help' to display the help menu.
> Traceback (most recent call last):
>   File "/usr/src/mytonctrl/mytonctrl.py", line 1216, in <module>
>     console.Run()
>   File "/usr/src/mytonctrl/mypyconsole/mypyconsole.py", line 97, in Run
>     self.startFunction()
>   File "/usr/src/mytonctrl/mytonctrl.py", line 106, in PreUp
>     check_vport()
>   File "/usr/src/mytonctrl/mytonctrl.py", line 122, in check_vport
>     vconfig = ton.GetValidatorConfig()
>   File "/usr/src/mytonctrl/mytoncore.py", line 1929, in GetValidatorConfig
>     result = self.validatorConsole.Run("getconfig")
>   File "/usr/src/mytonctrl/mytoncore.py", line 66, in Run
>     raise Exception("ValidatorConsole error: Validator console is not settings")
> Exception: ValidatorConsole error: Validator console is not settings
> ```

After reinstalling it, it works fine.

**Comment by lcgogo** [comment]
ubuntu 20.04 same issue
```shell
[debug]   31.05.2024, 14:14:40.568 (UTC)  <MainThread>  prepare vconfig
[debug]   31.05.2024, 14:14:40.568 (UTC)  <MainThread>  write vconfig
[debug]   31.05.2024, 14:14:40.569 (UTC)  <MainThread>  Start/restart validator service
[debug]   31.05.2024, 14:14:40.580 (UTC)  <MainThread>  sleep 10 sec
[debug]   31.05.2024, 14:14:50.589 (UTC)  <MainThread>  read mconfig
[debug]   31.05.2024, 14:14:50.591 (UTC)  <MainThread>  edit mytoncore config file
[debug]   31.05.2024, 14:14:50.591 (UTC)  <MainThread>  write mconfig
[debug]   31.05.2024, 14:14:50.594 (UTC)  <MainThread>  Start/restart mytoncore service
[debug]   31.05.2024, 14:14:50.624 (UTC)  <MainThread>  Backup validator config file 'config.json' to 'config.json.backup'
[debug]   31.05.2024, 14:14:50.626 (UTC)  <MainThread>  Backup mytoncore config file 'mytoncore.db' to 'mytoncore.db.backup'
[debug]   31.05.2024, 14:14:50.628 (UTC)  <MainThread>  start CreateSymlinks fuction
[4/4] Mytonctrl installation completed
ubuntu@blockchain-ton-replica:~$ sudo su -
root@blockchain-ton-replica:~# cd /var/
root@blockchain-ton-replica:/var# ls
backups  cache  crash  lib  local  lock  log  mail  opt  run  snap  spool  tmp  ton-work  www
root@blockchain-ton-replica:/var# ls -al
total 56
drwxr-xr-x 15 root      root      4096 May 31 10:49 .
drwxr-xr-x 20 root      root      4096 May 31 14:14 ..
drwxr-xr-x  2 root      root      4096 May 31 10:10 backups
drwxr-xr-x 14 root      root      4096 May 31 14:14 cache
drwxrwxrwt  2 root      root      4096 Apr 26 09:44 crash
drwxr-xr-x 45 root      root      4096 May 31 14:14 lib
drwxrwsr-x  2 root      staff     4096 Apr 15  2020 local
lrwxrwxrwx  1 root      root         9 Apr 26 09:42 lock -> /run/lock
drwxrwxr-x 12 root      syslog    4096 May 31 11:07 log
drwxrwsr-x  2 root      mail      4096 Apr 26 09:42 mail
drwxr-xr-x  2 root      root      4096 Apr 26 09:42 opt
lrwxrwxrwx  1 root      root         4 Apr 26 09:42 run -> /run
drwxr-xr-x  7 root      root      4096 Apr 26 09:48 snap
drwxr-xr-x  4 root      root      4096 Apr 26 09:42 spool
drwxrwxrwt  9 root      root      4096 May 31 14:17 tmp
drwxr-xr-x  4 validator validator   62 May 31 14:14 ton-work
drwxrwxr-x  3 www-data  www-data  4096 May 20 07:36 www
root@blockchain-ton-replica:/var# cd ton-work/
root@blockchain-ton-replica:/var/ton-work# ls
db  keys  log  log.thread1.log
root@blockchain-ton-replica:/var/ton-work# du -sh
1.7G	.
root@blockchain-ton-replica:/var/ton-work# cat /var/bin/ton/local.config.json
cat: /var/bin/ton/local.config.json: No such file or directory
root@blockchain-ton-replica:/var/ton-work# mytonctrl
[warning] 31.05.2024, 14:49:27.887 (UTC)  <MainThread>  The config file is broken
local.db: {'config': {'logLevel': 'info', 'isLimitLogFile': True, 'isDeleteOldLogFile': False, 'isIgnorLogWarning': False, 'isStartOnlyOneProcess': True, 'memoryUsinglimit': 50, 'isLocaldbSaving': False, 'isWritingLogFile': True}}
[debug]   31.05.2024, 14:49:27.887 (UTC)  <MainThread>  Thread self_test started
[debug]   31.05.2024, 14:49:27.888 (UTC)  <MainThread>  Thread write_log started
[info]    31.05.2024, 14:49:27.888 (UTC)  <MainThread>  Start program `/usr/src/mytonctrl/mytonctrl.py`
Welcome to the console. Enter 'help' to display the help menu.
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytonctrl.py", line 1228, in <module>
    console.Run()
  File "/usr/src/mytonctrl/mypyconsole/mypyconsole.py", line 97, in Run
    self.startFunction()
  File "/usr/src/mytonctrl/mytonctrl.py", line 114, in PreUp
    check_vport()
  File "/usr/src/mytonctrl/mytonctrl.py", line 130, in check_vport
    vconfig = ton.GetValidatorConfig()
  File "/usr/src/mytonctrl/mytoncore.py", line 1951, in GetValidatorConfig
    result = self.validatorConsole.Run("getconfig")
  File "/usr/src/mytonctrl/mytoncore.py", line 67, in Run
    raise Exception("ValidatorConsole error: Validator console is not settings")
Exception: ValidatorConsole error: Validator console is not settings
root@blockchain-ton-replica:/var/ton-work# exit
logout
ubuntu@blockchain-ton-replica:~$ mytonctrl
[warning] 31.05.2024, 14:49:33.425 (UTC)  <MainThread>  The config file is broken
local.db: {'config': {'logLevel': 'info', 'isLimitLogFile': True, 'isDeleteOldLogFile': False, 'isIgnorLogWarning': False, 'isStartOnlyOneProcess': True, 'memoryUsinglimit': 50, 'isLocaldbSaving': False, 'isWritingLogFile': True}}
[debug]   31.05.2024, 14:49:33.426 (UTC)  <MainThread>  Thread self_test started
[debug]   31.05.2024, 14:49:33.427 (UTC)  <MainThread>  Thread write_log started
[info]    31.05.2024, 14:49:33.427 (UTC)  <MainThread>  Start program `/usr/src/mytonctrl/mytonctrl.py`
Welcome to the console. Enter 'help' to display the help menu.
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytonctrl.py", line 1228, in <module>
    console.Run()
  File "/usr/src/mytonctrl/mypyconsole/mypyconsole.py", line 97, in Run
    self.startFunction()
  File "/usr/src/mytonctrl/mytonctrl.py", line 114, in PreUp
    check_vport()
  File "/usr/src/mytonctrl/mytonctrl.py", line 130, in check_vport
    vconfig = ton.GetValidatorConfig()
  File "/usr/src/mytonctrl/mytoncore.py", line 1951, in GetValidatorConfig
    result = self.validatorConsole.Run("getconfig")
  File "/usr/src/mytonctrl/mytoncore.py", line 67, in Run
    raise Exception("ValidatorConsole error: Validator console is not settings")
Exception: ValidatorConsole error: Validator console is not settings
ubuntu@blockchain-ton-replica:~$ which mytonctrl
/usr/bin/mytonctrl
```

**Comment by TemirAskhat** [comment]
What is the workaround and the resolution for this?

**Comment by tucher** [comment]
Same problem! 
`Exception: ValidatorConsole error: Validator console is not settings`

**Comment by gkozyrev** [comment]
Same problem!

<img width="1013" alt="image" src="https://github.com/ton-blockchain/mytonctrl/assets/27163035/7389230f-22cd-4895-9d01-0514c4610ba9">

**Comment by datacoder-io** [comment]
Fixed issue after reboot server and then run mytonctrl in root user

**Comment by jalilimmd** [comment]
The reboot does not work for me.
Has anyone found the solution except to install it in full mode?

**Comment by 420516460** [comment]
Still has this issue, has anyone work?

**Comment by 0x090909** [comment]
nothing works, I lost the whole dump that took me one day to download for this error

**Comment by 0x090909** [comment]
Plus the documentation is outdated!!!! https://docs.ton.org/participate/run-nodes/full-node 

this is supposed to be the next big thing, yet people who want to join the network have a very hard time
