### ISSUE TITLE
is there a way to reset installation ?

### ISSUE THREAD

**Issue by developer-devo** [ton-blockchain/mytonctrl#242]
Hi there, the download stopped midway and I;m now not able to restart teh installation process. It sayd 

```
[6/6] TON software installation complete
[3/4] Launching the mytoninstaller.py
[debug]   15.04.2024, 15:27:27.417 (UTC)  <MainThread>  Thread self_test started
[debug]   15.04.2024, 15:27:27.418 (UTC)  <MainThread>  Thread write_log started
[info]    15.04.2024, 15:27:27.418 (UTC)  <MainThread>  Start program `/usr/src/mytonctrl/mytoninstaller.py`
[debug]   15.04.2024, 15:27:27.418 (UTC)  <MainThread>  start FirstMytoncoreSettings fuction
Unit exist.
[warning] 15.04.2024, 15:27:27.420 (UTC)  <MainThread>  mytoncore.db already exist. Break FirstMytoncoreSettings fuction
[debug]   15.04.2024, 15:27:27.420 (UTC)  <MainThread>  start FirstNodeSettings fuction
[warning] 15.04.2024, 15:27:27.420 (UTC)  <MainThread>  Validators config.json already exist. Break FirstNodeSettings fuction
[debug]   15.04.2024, 15:27:27.420 (UTC)  <MainThread>  start EnableValidatorConsole function
[warning] 15.04.2024, 15:27:27.420 (UTC)  <MainThread>  Server or client key already exist. Break EnableValidatorConsole fuction
[debug]   15.04.2024, 15:27:27.420 (UTC)  <MainThread>  start EnableLiteServer function
[warning] 15.04.2024, 15:27:27.420 (UTC)  <MainThread>  Liteserver key already exist. Break EnableLiteServer fuction
[debug]   15.04.2024, 15:27:27.420 (UTC)  <MainThread>  Backup validator config file 'config.json' to 'config.json.backup'
[debug]   15.04.2024, 15:27:27.424 (UTC)  <MainThread>  Backup mytoncore config file 'mytoncore.db' to 'mytoncore.db.backup'
[debug]   15.04.2024, 15:27:27.427 (UTC)  <MainThread>  start CreateSymlinks fuction
[4/4] Mytonctrl installation completed
```
but when i do "mytonctrl" I get this error

`[warning] 15.04.2024, 15:28:25.859 (UTC)  <MainThread>  The config file is broken
local.db: {'config': {'logLevel': 'info', 'isLimitLogFile': True, 'isDeleteOldLogFile': False, 'isIgnorLogWarning': False, 'isStartOnlyOneProcess': True, 'memoryUsinglimit': 50, 'isLocaldbSaving': False, 'isWritingLogFile': True}}
[debug]   15.04.2024, 15:28:25.861 (UTC)  <MainThread>  Thread self_test started
[debug]   15.04.2024, 15:28:25.861 (UTC)  <MainThread>  Thread write_log started
[info]    15.04.2024, 15:28:25.861 (UTC)  <MainThread>  Start program `/usr/src/mytonctrl/mytonctrl.py`
Welcome to the console. Enter 'help' to display the help menu.
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytonctrl.py", line 1228, in <module>
    console.Run()
  File "/usr/src/mytonctrl/mypyconsole/mypyconsole.py", line 97, in Run
    self.startFunction()
  File "/usr/src/mytonctrl/mytonctrl.py", line 114, in PreUp
    check_vport()
  File "/usr/src/mytonctrl/mytonctrl.py", line 130, in check_vport
    vconfig = ton.GetValidatorConfig()
  File "/usr/src/mytonctrl/mytoncore.py", line 1951, in GetValidatorConfig
    result = self.validatorConsole.Run("getconfig")
  File "/usr/src/mytonctrl/mytoncore.py", line 67, in Run
    raise Exception("ValidatorConsole error: Validator console is not settings")
Exception: ValidatorConsole error: Validator console is not settings
`

I need to reset the installation and start it from scratch

how to do it ?

**Comment by developer-devo** [comment]
@igroman787 can you help with this ?
