### ISSUE TITLE
[Errno 2] No such file or directory: '/var/ton-work/db'

### ISSUE THREAD

**Issue by LuckyCoders** [ton-blockchain/mytonctrl#278]
Ubuntu 20.04 LTS (Focal Fossa)

```
:~# mytonctrl
[debug]   29.05.2024, 18:21:17.405 (UTC)  <MainThread>  Thread self_test started
[debug]   29.05.2024, 18:21:17.405 (UTC)  <MainThread>  Thread write_log started
[info]    29.05.2024, 18:21:17.405 (UTC)  <MainThread>  Start program `/usr/src/mytonctrl/mytonctrl.py`
Welcome to the console. Enter 'help' to display the help menu.
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytonctrl.py", line 1228, in <module>
    console.Run()
  File "/usr/src/mytonctrl/mypyconsole/mypyconsole.py", line 97, in Run
    self.startFunction()
  File "/usr/src/mytonctrl/mytonctrl.py", line 113, in PreUp
    CheckDiskUsage()
  File "/usr/src/mytonctrl/mytonctrl.py", line 233, in CheckDiskUsage
    usage = ton.GetDbUsage()
  File "/usr/src/mytonctrl/mytoncore.py", line 2766, in GetDbUsage
    data = psutil.disk_usage(path)
  File "/usr/local/lib/python3.8/dist-packages/psutil/__init__.py", line 2049, in disk_usage
    return _psplatform.disk_usage(path)
  File "/usr/local/lib/python3.8/dist-packages/psutil/_psposix.py", line 185, in disk_usage
    st = os.statvfs(path)
FileNotFoundError: [Errno 2] No such file or directory: '/var/ton-work/db'
```

**Comment by Mountain-AI** [comment]
me too:


[6/6] TON software installation complete
[3/4] Launching the mytoninstaller.py
[debug]   05.06.2024, 07:47:16.380 (UTC)  <MainThread>  Thread self_test started
[debug]   05.06.2024, 07:47:16.381 (UTC)  <MainThread>  Thread write_log started
[info]    05.06.2024, 07:47:16.381 (UTC)  <MainThread>  Start program `/usr/src/mytonctrl/mytoninstaller.py`
[debug]   05.06.2024, 07:47:16.381 (UTC)  <MainThread>  start FirstMytoncoreSettings fuction
Created symlink /etc/systemd/system/multi-user.target.wants/mytoncore.service → /etc/systemd/system/mytoncore.service.
[debug]   05.06.2024, 07:47:18.460 (UTC)  <MainThread>  Start/restart mytoncore service
[debug]   05.06.2024, 07:47:18.474 (UTC)  <MainThread>  start CreateSymlinks fuction
[4/4] Mytonctrl installation completed
cc@cc:~$ mytonctrl
[debug]   05.06.2024, 07:47:31.521 (UTC)  <MainThread>  Thread self_test started
[debug]   05.06.2024, 07:47:31.522 (UTC)  <MainThread>  Thread write_log started
[info]    05.06.2024, 07:47:31.523 (UTC)  <MainThread>  Start program `/usr/src/mytonctrl/mytonctrl.py`
Welcome to the console. Enter 'help' to display the help menu.
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytonctrl.py", line 1228, in <module>
    console.Run()
  File "/usr/src/mytonctrl/mypyconsole/mypyconsole.py", line 97, in Run
    self.startFunction()
  File "/usr/src/mytonctrl/mytonctrl.py", line 113, in PreUp
    CheckDiskUsage()
  File "/usr/src/mytonctrl/mytonctrl.py", line 233, in CheckDiskUsage
    usage = ton.GetDbUsage()
  File "/usr/src/mytonctrl/mytoncore.py", line 2766, in GetDbUsage
    data = psutil.disk_usage(path)
  File "/usr/local/lib/python3.8/dist-packages/psutil/__init__.py", line 2049, in disk_usage
    return _psplatform.disk_usage(path)
  File "/usr/local/lib/python3.8/dist-packages/psutil/_psposix.py", line 185, in disk_usage
    st = os.statvfs(path)
FileNotFoundError: [Errno 2] No such file or directory: '/var/ton-work/db'

**Comment by Mountain-AI** [comment]
https://github.com/ton-blockchain/mytonctrl/blob/master/mytoninstaller.py#L330
https://dump.ton.org

I hope it will be helpful to everyone, as it has solved my problem

**Comment by awesome-doge** [comment]
> Ubuntu 20.04 LTS (Focal Fossa)
> 
> ```
> :~# mytonctrl
> [debug]   29.05.2024, 18:21:17.405 (UTC)  <MainThread>  Thread self_test started
> [debug]   29.05.2024, 18:21:17.405 (UTC)  <MainThread>  Thread write_log started
> [info]    29.05.2024, 18:21:17.405 (UTC)  <MainThread>  Start program `/usr/src/mytonctrl/mytonctrl.py`
> Welcome to the console. Enter 'help' to display the help menu.
> Traceback (most recent call last):
>   File "/usr/src/mytonctrl/mytonctrl.py", line 1228, in <module>
>     console.Run()
>   File "/usr/src/mytonctrl/mypyconsole/mypyconsole.py", line 97, in Run
>     self.startFunction()
>   File "/usr/src/mytonctrl/mytonctrl.py", line 113, in PreUp
>     CheckDiskUsage()
>   File "/usr/src/mytonctrl/mytonctrl.py", line 233, in CheckDiskUsage
>     usage = ton.GetDbUsage()
>   File "/usr/src/mytonctrl/mytoncore.py", line 2766, in GetDbUsage
>     data = psutil.disk_usage(path)
>   File "/usr/local/lib/python3.8/dist-packages/psutil/__init__.py", line 2049, in disk_usage
>     return _psplatform.disk_usage(path)
>   File "/usr/local/lib/python3.8/dist-packages/psutil/_psposix.py", line 185, in disk_usage
>     st = os.statvfs(path)
> FileNotFoundError: [Errno 2] No such file or directory: '/var/ton-work/db'
> ```

Regarding the question you raised, I would like to know whether there are any files under this path `/var/ton-work/db`.

**Comment by satoshix13** [comment]
> https://github.com/ton-blockchain/mytonctrl/blob/master/mytoninstaller.py#L330 https://dump.ton.org
> 
> I hope it will be helpful to everyone, as it has solved my problem

Hi, i am still strugling. Can you explain how you solved it please
