### ISSUE TITLE
Mytonctl2 status error

### ISSUE THREAD

**Issue by nooperpudd** [ton-blockchain/mytonctrl#321]
```
Aug  8 03:25:00 ton-new python3[597]: #033[31m#033[1m[error]   #033[0m08.08.2024, 03:20:40.835 (UTC)  #033[31m#033[1m<save_db>     #033[0msave_db error: lock_file error: time out.
Aug  8 03:25:00 ton-new python3[597]: #033[35m#033[1m[debug]   #033[0m08.08.2024, 03:20:48.540 (UTC)  #033[32m#033[1m<Telemetry>   #033[0mstart GetFullElectorAddr function
Aug  8 03:25:00 ton-new python3[597]: #033[35m#033[1m[debug]   #033[0m08.08.2024, 03:20:48.553 (UTC)  #033[32m#033[1m<Telemetry>   #033[0mstart GetActiveElectionId function
Aug  8 03:25:00 ton-new python3[597]: #033[35m#033[1m[debug]   #033[0m08.08.2024, 03:20:48.592 (UTC)  #033[32m#033[1m<Telemetry>   #033[0mstart GetConfig32 function
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:05.070 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:06.071 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:07.073 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:08.073 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:09.075 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[35m#033[1m[debug]   #033[0m08.08.2024, 06:52:09.157 (UTC)  #033[32m#033[1m<ScanLiteServers>#033[0mstart GetValidatorStatus function
Aug  8 06:52:49 ton-new python3[47698]: #033[33m#033[1m[warning] #033[0m08.08.2024, 06:52:09.166 (UTC)  #033[32m#033[1m<ScanLiteServers>#033[0mGetValidatorStatus warning: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:10.077 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:11.078 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:11.538 (UTC)  #033[31m#033[1m<save_db>     #033[0msave_db error: lock_file error: time out.
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:12.079 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:13.081 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:14.081 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:15.083 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:16.084 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:16.563 (UTC)  #033[31m#033[1m<save_db>     #033[0msave_db error: lock_file error: time out.
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:17.085 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:18.087 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:19.088 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:20.089 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:21.091 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:21.588 (UTC)  #033[31m#033[1m<save_db>     #033[0msave_db error: lock_file error: time out.
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:22.015 (UTC)  #033[31m#033[1m<custom_overlays>#033[0mcustom_overlays error: lock_file error: time out.
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:22.092 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:23.093 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:24.095 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:25.096 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:26.097 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:27.099 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:28.100 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:29.102 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:30.103 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:31.104 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:31.621 (UTC)  #033[31m#033[1m<save_db>     #033[0msave_db error: lock_file error: time out.
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:32.106 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:33.107 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:34.108 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:35.110 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:36.111 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:37.112 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:38.113 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:39.115 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:40.116 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:41.117 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:41.652 (UTC)  #033[31m#033[1m<save_db>     #033[0msave_db error: lock_file error: time out.
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:42.119 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:43.120 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:44.121 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:45.123 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:46.124 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:47.125 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
Aug  8 06:52:49 ton-new python3[47698]: #033[31m#033[1m[error]   #033[0m08.08.2024, 06:52:48.127 (UTC)  #033[31m#033[1m<self_test>   #033[0mself_test error: '>' not supported between instances of 'float' and 'NoneType'
```

mytonctl 

```
ubuntu@ton-new:/var/log$ mytonctrl
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/mytonctrl/__main__.py", line 4, in <module>
    mytonctrl()
  File "/usr/local/lib/python3.8/dist-packages/mytonctrl/mytonctrl.py", line 1517, in mytonctrl
    Init(local, ton, console, sys.argv[1:])
  File "/usr/local/lib/python3.8/dist-packages/mytonctrl/mytonctrl.py", line 135, in Init
    if ton.using_validator():
  File "/usr/local/lib/python3.8/dist-packages/mytoncore/mytoncore.py", line 3323, in using_validator
    return self.get_mode_value('validator')
  File "/usr/local/lib/python3.8/dist-packages/mytoncore/mytoncore.py", line 3305, in get_mode_value
    current_modes = self.get_modes()
  File "/usr/local/lib/python3.8/dist-packages/mytoncore/mytoncore.py", line 3273, in get_modes
    self.migrate_to_modes()
  File "/usr/local/lib/python3.8/dist-packages/mytoncore/mytoncore.py", line 3261, in migrate_to_modes
    self.local.save()
  File "/usr/local/lib/python3.8/dist-packages/mypylib/mypylib.py", line 614, in save
    self.save_db()
  File "/usr/local/lib/python3.8/dist-packages/mypylib/mypylib.py", line 610, in save_db
    self.write_db(self.db)
  File "/usr/local/lib/python3.8/dist-packages/mypylib/mypylib.py", line 497, in write_db
    self.lock_file(db_path)
  File "/usr/local/lib/python3.8/dist-packages/mypylib/mypylib.py", line 510, in lock_file
    raise Exception("lock_file error: time out.")
Exception: lock_file error: time out.
```

**Comment by nooperpudd** [comment]
just delete `~/.local/share/` `mytoncore  mytonctrl  mytoninstaller`. and re-install
