### ISSUE TITLE
[BUG] error when install mytonctrl

### ISSUE THREAD

**Issue by macrocan** [ton-blockchain/mytonctrl#359]
First，I select validator, Mainnet and signle pool
```
[?] Select installation mode (More on https://docs.ton.org/participate/nodes/node-types):
 > validator
   liteserver

[?] Select network:
 > Mainnet
   Testnet
   Other

[?] Select mode for validator usage. You can skip and set up this later:
   Validator wallet
   Nominator pool
 > Single pool
   Liquid Staking
   Skip

[?] Do you want to download blockchain's dump? This reduces synchronization time but requires to download a large file (y/N): y

bash install.sh  -n mainnet -m single-pool -d
```

Finally, some error happen 
```
Local DB path: /home/op/.local/share/mytoncore/mytoncore.db
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/mytoncore/__main__.py", line 5, in <module>
    mytoncore()
  File "/usr/local/lib/python3.10/dist-packages/mytoncore/functions.py", line 581, in mytoncore
    Init(local)
  File "/usr/local/lib/python3.10/dist-packages/mytoncore/functions.py", line 32, in Init
    Event(local, event_name)
  File "/usr/local/lib/python3.10/dist-packages/mytoncore/functions.py", line 59, in Event
    enable_mode(local, event_name)
  File "/usr/local/lib/python3.10/dist-packages/mytoncore/functions.py", line 101, in enable_mode
    ton.enable_mode(mode)
  File "/usr/local/lib/python3.10/dist-packages/mytoncore/mytoncore.py", line 3058, in enable_mode
    raise Exception(f'Unknown module name: {name}. Available modes: {", ".join(MODES)}')
Exception: Unknown module name: single-pool. Available modes: validator, nominator-pool, single-nominator, liquid-staking, liteserver
[5/5] Mytonctrl installation completed
```

Mytonctrl had installed successfully，but failed to download blockchain's dump and single norminator pool mode is not enabled

**Comment by yungwine** [comment]
Thank you, fixed in https://github.com/ton-blockchain/mytonctrl/pull/360
