### ISSUE TITLE
toncenter index page

### ISSUE THREAD

**Issue by nekulin** [ton-blockchain/mytonctrl#64]
Run 
`/usr/bin/python3 -m pyTON --liteserverconfig /usr/bin/ton/local.config.json --libtonlibjson /usr/bin/ton/tonlib/libtonlibjson.so`

Get http://ip:8000

Error console

`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpv0vd_qdg'
Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiohttp-3.8.1-py3.8-linux-x86_64.egg/aiohttp/web_protocol.py", line 514, in start
    resp, reset = await task
  File "/usr/local/lib/python3.8/dist-packages/aiohttp-3.8.1-py3.8-linux-x86_64.egg/aiohttp/web_protocol.py", line 460, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp-3.8.1-py3.8-linux-x86_64.egg/aiohttp/web_protocol.py", line 613, in finish_response
    await prepare_meth(request)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp-3.8.1-py3.8-linux-x86_64.egg/aiohttp/web_fileresponse.py", line 142, in prepare
    st: os.stat_result = await loop.run_in_executor(None, filepath.stat)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpf3st1jyu'`

**Comment by igroman787** [comment]
fix: https://github.com/ton-blockchain/mytonctrl/commit/c136b6a3750d087884a33907598b6d6bdb984667
